### ISSUE TITLE
error on grep

### ISSUE THREAD

**Issue by bylli79** [vacosta94/VirtBKP#7]
Hello,
use centos 7.
By performing the backup I have the following error:
the grep: / sys / block / * / serial command returns me the file not found error.
I tried to use version 1.3 but it goes into timeout.
What can I do?

Thank you

**Comment by vacosta94** [comment]
Hi! please give  more details about your environment
You have a "bkpvm" where you execute the script and you get that error there?
- Is your "bkpvm" on the same oVirt's Site?
- If you have more than 1 physical node, is your storage domain a shared storage? 

Is your CentOS 7 a virtual machine or a container? Because the /sys/block is a standard OS folder and it's very weird if that does not exist on your system

Regards

**Comment by vacosta94** [comment]
Please check is your disks are attached as Virtio or Virtio-SCSI device.

Regards
